language: java
jdk: openjdk11
env:
  global:
  - secure: Ap7eFV0Aktlu2npCVZqfNdNAvkzkLpJcOZzM910Myc3UGGbz4rojastzvHVV15JAqQOH44VchJMtc2UMovEwKmhWkweXwIIMxkFrzspLkv/MHWRz7wK/HlnGvv4THnxgY3cl+BEZasu4SWbaSLvtcIgSJKsXNqckfIQ/8FzzuHRdlclPxfj8TY+vsbkTSKw2cSh6WtUJrzP8nqABPeWD9fvns87JXzwGhMm0DgQOn3VsFTuWwShlAbct/15Sw37oMp/2Dc43dXyyBO8JvkMWo+1C6/v8ttvc5MF2/Ba4hbpMeIw3LTTSb04MyrpVSBtdBY6Fv/NpILmrMczOoJ/xIwLQ+nvGDGMD+hdHN90EVj44L62/FLTcasxnOpPbyV1xOXTSvKhLKeznZLbOY1gLKfTMRenh1MwJ9SEWxoFMH5H6MWTlxJq1YjnNgckRt4pHe01gwS/3zd/YfIRRhzQw9vVLJcP7gC4G7H4G4mWlYNWie02L0A1I+1HEY+kvjf29viK1PZwKSfXtkwtZ+Q4fyw5ubLLz3PfRrb4JL384yNiDJuq2I/lzzPjOp6tdZsWV1tfCNxHCQDdsdQWYTaa8dlP9qaAo2tbbxdou1m1zSvDgcXz5mxEZDp4iYSiDLU5rVyv8N/h13Bw3QOicluSy0l73sMUn7FSG/4U1ahVis1Y=
  - secure: jTdTFQlpX95K3BBkFj/IiM4lEXeVUJ0EyMxh1PsOd3rc7CkYPPBJO2jUBRY13oamkU9uv/GAniyB1OtVNCX1meSx6HXcGNS4jwAdNvWctwj94QtiSU3w3Te8VTK+UluREvTV97J00g/O+EVzNMzR7GCeWHhdbmQtrHKn6y8Q95O3VnZ0krLyfS7+QEHB5g2KavQpfJSO1eRNIiDs5O1dfkD03QEXQ0CgzNpoR6PeIUByXox5YnLMAbyk3kkljyIDqJtEOVVX0ssyu9RcmTTElwv5naz+fsj1J7LTLSdjQJxFAfSr18rOL6Mf1j0k4Y3gV2+tdg5caLYtlB8r9SRX7A++22pD8Cit3qmO3lNeccP+RXO0vg4rk0xvZI+LcUBwBzjZrZHgfmrkVN3bN3pCkxI0X8D2JlnJ1ioND0RAnR6ERPgQZ07TSzEhi5KRaTAt0/6DvXw9HCEkKrIcP5YCBoK4I/66AiKqgs5Ba3vQjVXRoEhfQhYMW99fsl4dDzl6nvfir4z5oaPYJnHl9du3VTS+ZKN6h9mkXiHlQ109YqXs0Uw6o6n13BpEqrhpj2C7KaB8ex98W8iCOD742AwnC9jLOmjr5nXrkEaX7HQSrmVkQuSHalrdQAZNxCIbSqDY6Sz9WXWkbQ6P8KN0Q40F1ni8Vqzm/SwXlLvg/yqxwAY=
install: skip
script: mvn --settings .mvn/settings.xml install && ([[ $TRAVIS_BRANCH != "master" ]] || mvn --settings .mvn/settings.xml -DskipTests=true deploy)
cache:
  directories: "$HOME/.m2"
branches:
  except: gh-pages
notifications:
  email: joerg.hohwiller@googlemail.com
